apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: basic-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-rest
  template:
    metadata:
      labels:
        app: basic-rest
    spec:
      containers:
        - name: basic-rest
          image: am0072008/rest-java-spring:1.3
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: mysql-host
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: basic-rest-secret
                  key: mysql-user-id
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: basic-rest-secret
                  key: mysql-user-pass
            - name: DUMMY_SA
              value: /var/secrets/sample-secret.json # make sure the file name matches with the file during the secret creation.
          volumeMounts:
            - name: application-secret
              mountPath: /var/secrets/
      volumes:
        - name: application-secret
          secret:
            secretName: sample-secret


---

apiVersion: v1
kind: Service
metadata:
  name: basic-rest-service
spec:
  selector:
    app: basic-rest
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # port for external IP/ port you need to mention in browser.(Optional)
