pipeline {

  agent any

  environment {
    TEST1 = "ola"
  }

  stages {

    stage("build") {
      steps {
        echo "Build jobs"
      }
    }

    stage("deploy") {
    environment {
      TEST2 = "ola2"
    }
      when {
        expression { env.BRANCH_NAME=="master"} // jenkins provided env variables
      }
      steps {
        echo "Deploy jobs $TEST2 and $TEST1"
      }
    }
  }

  post {
  // for status of build end of execution
    always {
      echo "Always"
    }
    success {
      echo "Success"
    }
    failure {
      echo "failure"
    }
  }

}
