pipeline {

  agent any

  stages {

    stage("build") {
      steps {
        echo "Build jobs"
      }
    }

    stage("deploy") {
      when {
        expression { env.BRANCH_NAME="master"} // jenkins provided env variables
      }
      steps {
        echo "Deploy jobs"
      }
    }
  }

  post {
  // for status of build end of execution
    always {
      echo "Always"
    }
    success {
      echo "Success"
    }
    failure {
      echo "failure"
    }
  }

}
